name: Build LaTeX document
on: 
  workflow_dispatch:
  push:
    paths:
      - '**.tex'
      - 'figures/**'
      - 'bib/**'
      - '**.bib'
    branches:
      - master
      
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: Latest Compiled Report
          files: main.pdf
      
